### ISSUE TITLE
fragmentMap vUv is always == 0.0?

### ISSUE THREAD

**Issue by supermoos** [zadvorsky/three.bas#15]
I've run into a weird / and hard to debug issue with BasicAnimationMaterial and options.fragmentMap where the vUv is always a = vec2(0.0, 0.0).

Here's some pseudo code of the setup abstracted from my general code:
```
var options = {uniformValues: {}}
options.uniformValues.map = new THREE.TextureLoader().load('assets/textures/uv_grid.jpg');

options.fragmentMap = [
	'if (vUv.x == 0.0) {',
	'diffuseColor = vec4(1.0, 0.0, 0.0, 1.0);',
	'} else {',
	'vec4 texelColor1 = texture2D(map, vUv);',
	'diffuseColor *= texelColor1;',
'}'
];
```
my geometry is instanced like this:

```
let planeTest = new THREE.PlaneGeometry(0.5, 0.5, 1.0, 1.0);
		let geometry = new BAS.PrefabBufferGeometry(planeTest, 6);
		geometry.computeVertexNormals();
		geometry.bufferUvs();
let material = new BAS.BasicAnimationMaterial(materialOptions);
```

I've confirmed that vUv never changes from 0.0, 0.0 because i see 6 completely red planes rendered.

Any idea / suggestions of how to debug this?

**Comment by clindsey** [comment]
I think the texture is supposed to be assigned to `map.value`, like in [this example](https://github.com/zadvorsky/three.bas/blob/86931253240abadf68b7c62edb934b994693ed4a/examples/materials_phong/main.js#L213)

**Comment by zadvorsky** [comment]
@supermoos do you have an example of this running anywhere?

**Comment by zadvorsky** [comment]
Going to close this to clean up the old open issues.
