### ISSUE TITLE
bufferUVs vs bufferUvs - typo?

### ISSUE THREAD

**Issue by clindsey** [zadvorsky/three.bas#16]
These two classes have the same method but they're spelled slightly differently - 
 
http://three-bas-examples.surge.sh/docs/gen/THREE.BAS.PrefabBufferGeometry.html#bufferUvs__anchor

http://three-bas-examples.surge.sh/docs/gen/THREE.BAS.ModelBufferGeometry.html#bufferUVs__anchor

**Comment by zadvorsky** [comment]
I'll make it consistent in the next minor release
