### ISSUE TITLE
this.BufferIndices is not a function

### ISSUE THREAD

**Issue by L03TJ3** [zadvorsky/three.bas#20]
When trying to run the Image-transition example, I get this error
from bas.min.js.

Anyone knows the cause??

**Comment by L03TJ3** [comment]
I dont know if this is usefull, but it occurs when its a SlideGeometry?

**Comment by zadvorsky** [comment]
Can you share some of the source code where this is occuring? Also, what's a slide geometry?

**Comment by L03TJ3** [comment]
Sure, and SlideGeometry is what $this refers to after BufferGeometry.call(this)
SlideGeometry of type BufferGeometry (im just starting with your library, so im not sure on specifics).
The following is from ModelBufferGeometry.js:
`function ModelBufferGeometry(model, options) {
  BufferGeometry.call(this);

  /**
   * A reference to the geometry used to create this instance.
   * @type {THREE.Geometry}
   */
  this.modelGeometry = model;

  /**
   * Number of faces of the model.
   * @type {Number}
   */
  this.faceCount = this.modelGeometry.faces.length;

  /**
   * Number of vertices of the model.
   * @type {Number}
   */
  this.vertexCount = this.modelGeometry.vertices.length;

  options = options || {};
  options.computeCentroids && this.computeCentroids();

  this.bufferIndices();
  this.bufferPositions(options.localizeFaces);
}
ModelBufferGeometry.prototype = Object.create(BufferGeometry.prototype);
ModelBufferGeometry.prototype.constructor = ModelBufferGeometry;

/**
 * Computes a centroid for each face and stores it in THREE.BAS.ModelBufferGeometry.centroids.
 */
ModelBufferGeometry.prototype.computeCentroids = function() {
  /**
   * An array of centroids corresponding to the faces of the model.
   *
   * @type {Array}
   */
  this.centroids = [];

  for (let i = 0; i < this.faceCount; i++) {
    this.centroids[i] = Utils.computeCentroid(this.modelGeometry, this.modelGeometry.faces[i]);
  }
};

ModelBufferGeometry.prototype.bufferIndices = function() {
  const indexBuffer = new Uint32Array(this.faceCount * 3);

  this.setIndex(new BufferAttribute(indexBuffer, 1));

  for (let i = 0, offset = 0; i < this.faceCount; i++, offset += 3) {
    const face = this.modelGeometry.faces[i];

    indexBuffer[offset    ] = face.a;
    indexBuffer[offset + 1] = face.b;
    indexBuffer[offset + 2] = face.c;
  }
};

**Comment by zadvorsky** [comment]
Did you ever resolve this issue @L03TJ3 ? If I run the examples locally, everything works.

**Comment by L03TJ3** [comment]
I hadn't been able to look at it yet. I just tried a few things out, and still couldn't resolve the issue.
Then I found out I have a different version of /examples/image-transition/main.js.
But what the cause is in that other version, is a real mystery.
But no issue for here, thus this can be closed I guess!
