### ISSUE TITLE
how to set color or texture on LambertAnimationMaterial

### ISSUE THREAD

**Issue by HypnosNova** [zadvorsky/three.bas#22]
Is there any way to set color or texture in LambertAnimationMaterial and other AnimationMaterial, if i set color in it, it shows that 'color' is not a property of this material.

So all the materials' color is white or it could be change in some different ways

**Comment by zadvorsky** [comment]
To change the color, you need to set `diffuse` in `uniformValues`, like [here](https://github.com/zadvorsky/three.bas/blob/master/examples/model_face_animation/main.js#L110-L112). You can also change `material.uniforms.diffuse.value` on the material instance.
