### ISSUE TITLE
How do I change an opacity for each prefab using a PrefabBufferGeometry?

### ISSUE THREAD

**Issue by ArthurBardakov** [zadvorsky/three.bas#25]
What if I have a PrefabBufferGeometry, but I just wanna change the opacity for each prefab separately in the fragment shader using StandardAnimationMaterial, is it possible to achieve this? Or after PrefabBufferGeometry creation it is considered as one object?

**Comment by zadvorsky** [comment]
There are a few ways you can fo this.

You could create an attribute (let's say aOpacity), with 1 number per prefab. Then you need to pass this value to a varying vOpacity, so it can be used in the fragment shader as diffuseColor.a = vOpacity.

The Standard Material example should have what you need.

Also don't forget to set material.transparent to true

**Comment by ArthurBardakov** [comment]
The thing is that I did exactly like you said, but I didn't really seem to notice any changes (or at least not clear ones), `cause PrefabBufferGeometry was constructed from ExtrudeGeometry which depth parameter was making opacity not really clear. But anyways thanks for the answer and for the library too!!)

**Comment by ArthurBardakov** [comment]
Wanted to ask one more question that concerns the matter a little...I've been trying to make a dynamic background using PlaneGeometry or separate triangles that would move dynamically by changing vertices positions. If I make it using PlaneGeometry with BAS.ModelBufferGeometry and change vertexPositions, it works just fine and have a dynamic effect, but as a result I cannot change opacity for separate faces, as it is one object. And If I try to make like separate triangles in order to change opacity for each one, I loose a holistic effect of moving (connected) faces, which I have with PlaneGeometry . Is it even possible to make it or not? Will appriciate any advice one the matter!
