### ISSUE TITLE
Can three.bas be used to achieve gltf model animation?

### ISSUE THREAD

**Issue by dinglei19** [zadvorsky/three.bas#26]
In my project, I want to achieve a scene in which many vehicles are driving. Now I hava a glb car model , Can three.bas be used to achieve this scene ?

**Comment by zadvorsky** [comment]
Depends on the complexity of the car model. If it's a single geometry, you
can just use it as a prefab. If the model has several geometries /
materials, you could try a MultiPrefabGeometry, though I haven't used it
that way. Either way you will be limited by the number of vertices in the
model.
