### ISSUE TITLE
Text Animations

### ISSUE THREAD

**Issue by schechenkin** [zadvorsky/three.bas#29]
Found this examples:
https://codepen.io/collection/ABaxyy/

Realy love it! But seems it works only with old versions of Three.js and Three.bas libs. Is anyware working examples with newer libs versions?

**Comment by zadvorsky** [comment]
Hey.

Unfortunately these demos are pretty old, and I haven't updated them in
a while. I'm sure there's gonna be some breaking changes for more recent
versions.
I have been thinking about updating and bundling them, but I'm not sure
when / if I'll get around to it.
