### ISSUE TITLE
Prefab Geometry vs. Instanced Geometry

### ISSUE THREAD

**Issue by juliekoubova** [zadvorsky/three.bas#31]
Hello 😄 What is the difference between prefab geometry in three-bas and instanced geometry in three.js itself? They seem kinda similar to me, but I'm probably missing something basic.

I'm sorry, I know this is not really an issue. Is there a better place to ask these questions? Thank you ❤️

**Comment by zadvorsky** [comment]
Asking questions here is fine, at least for now.

When I first created this extension, THREE.js instanced geometries didn't exist (or I didn't know about them). Instanced geometries rely on [a WebGL extension](https://developer.mozilla.org/en-US/docs/Web/API/ANGLE_instanced_arrays) that changes how vertex attributes are used. This extension is fairly widely supported, but may be missing on some devices / browsers.

With instanced geometries, the default geometry attributes (position, normal, uv) are stored once (this defines the instance). Additional custom attributes (like a position / rotation / scale offset) are then stored once per instance.

With the prefab geometry, the default geometry attributes are simply duplicated, and custom attributes are stored once per vertex.

Instanced geometries are substantially more memory efficient, but you lose some flexibility; you can't have per-vertex variations for custom attributes, or per-instance variations for default attributes.

I recently added `InstancedPrefabBufferGeometry`, which which has a similar API as `PrefabBufferGeometry`, but uses the instanced geometry under the hood. See [this](https://github.com/zadvorsky/three.bas/blob/master/examples/instanced_prefabs/main.js) example.

**Comment by zadvorsky** [comment]
Yes, all three-bas materials should work with InstancedBufferGeometry (or any other buffer geometry). As you can see in the [source](https://github.com/zadvorsky/three.bas/blob/master/src/geometry/InstancedPrefabBufferGeometry.js), InstancedPrefabBufferGeometry is a thin wrapper that only copies the api from my other geometries.
