### ISSUE TITLE
DepthAnimationMaterial: Problem casting shadows taking alpha into account

### ISSUE THREAD

**Issue by martenzander** [zadvorsky/three.bas#32]
Hi @zadvorsky,

I have a little problem using the DepthAnimationMaterial. I have a scene with a bunch of instanced grass tufts using the InstancedPrefabBufferGeometry. I want them tufts to cast shadows taking their map's alpha into account. See the image below for an example based on MeshStandardMaterial and MeshDepthMaterial:

[Example](https://i.imgur.com/RY6YVxW.jpg)

In order to achieve this, I have to pass the following parameters to the MeshDepthMaterial in THREE.JS

`{
depthPacking: THREE.RGBADepthPacking,
map: MY_TEXTURE,
alphaTest: 0.5,
}`.

adding these properties to my DepthAnimationMaterial has no effect besides that shadows disappear. I have the feeling I am missing something fundamental, so I would be very thankful if you could point me in the right direction :)

Thanks in advance and keep up the work!

**Comment by zadvorsky** [comment]
Hey. I haven't tested BAS with any of those features, so there's a good
chance I'd need to add some code to support this. I won't be near a
computer until Monday, but I'll take a look then if you're still having
trouble.

**Comment by SlimMarten** [comment]
thanks, I'd really appreciate it

**Comment by zadvorsky** [comment]
Hello again.

I figured out what's happening, but I'll need more time to implement a proper fix. In the meantime, you'll need to do this:

In your animation material, add a alpha test define, and make sure the depthPacking is under uniformValues.

```
const material = new StandardAnimationMaterial({
  defines: {
    'ALPHATEST': 0.5
  },
  uniformValues: {
    alphaMap: alphaMapTexture,
    depthPacking: THREE.RGBADepthPacking
  }
})
```
Then when creating the depth material, set the needsUpdate flag for your alpha map.

```
mesh.customDepthMaterial = BAS.Utils.createDepthAnimationMaterial(material);
mesh.customDepthMaterial.uniforms.alphaMap.value.needsUpdate = true;
```
And everything should work, hopefully.

**Comment by SlimMarten** [comment]
Unfortunately no, still no shadows appearing

**Comment by zadvorsky** [comment]
[Here's](https://codepen.io/zadvorsky/pen/d286d173a219432896ed734d56fcf67a?editors=0010) a reduced test case with a BAS animation material + alpha map + custom depth material. Can you work from there and see what isn't working for you?

**Comment by SlimMarten** [comment]
thanks for the effort, I will test this as soon as I am back to work.

**Comment by SlimMarten** [comment]
hmm still not working. Also added `side: THREE.DoubleSide` now. As soon as I add 'ALPHATEST': 0.5; to my defines, shadows disappear completely.

**Comment by SlimMarten** [comment]
Unfortunatley no, it would take some time to isolate the code from the rest of my project. Since your demos are working well, I guess the reason for the issue is stuck somewhere else in my code.

As long as I can't confirm the existence of the issue we can consider this as resolved.
