### ISSUE TITLE
Using a normalMap uniformValue along with ToonAnimationMaterial causes shader compile error

### ISSUE THREAD

**Issue by SlimMarten** [zadvorsky/three.bas#33]
I am trying to create a BAS.ToonAnimationMaterial() using a normalMap in the uniformValues like so:

```
const material = new BAS.ToonAnimationMaterial({
			name: 'Material',
			extensions: {
				derivates: true
			},
			uniformValues: {
				normalMap: SOME TEXTURE HERE
			}
		})
```

This causes the following error:

> ERROR: 0:784: 'GL_OES_standard_derivatives' : extension is disabled

As soon as I remove the normalMap property from the uniformValues everything works as expected.

**Comment by zadvorsky** [comment]
You might have to enable the extension in `WebGLRenderer.extenstions` first, something like `renderer.extensions.get('GL_OES_standard_derivatives')` (this should return true/an object if the extension is supported, false otherwise). Though I think three.js does this by default. Maybe your system doesn't support it?

**Comment by zadvorsky** [comment]
Or maybe I need to add some logic to handle the extensions object... I'll check it out later today.

**Comment by zadvorsky** [comment]
Looking at the source code, passing an extension object should work. I did notice a typo in the code you posted; it should be `derivatives: true`, not `derivates: true`. Does changing that fix it?

**Comment by SlimMarten** [comment]
Okay, my bad. So sorry, the typing error of `derivatives` fixed it. I copied it from a foreign source and didn't check it twice. This one can be closed.

**Comment by zadvorsky** [comment]
Cool. Good to know it works.
