### ISSUE TITLE
Is this library still supported?

### ISSUE THREAD

**Issue by alexander-macleod** [zadvorsky/three.bas#53]
Seems that it doesnt work anymore with newer versions of Three.js

**Comment by zadvorsky** [comment]
I'm on vacation this week, but I'll take a look after I'm back.

**Comment by ampersand-alex** [comment]
no worries. have a good one.

if it helps, it looks like r108 of three.js broke it:

"THREE.ShaderMaterial: .shading has been removed. Use the boolean .flatShading instead."
"THREE.ShaderMaterial: .shading has been removed. Use the boolean .flatShading instead."
"THREE.WebGLProgram: shader error: " 0 "35715" false "gl.getProgramInfoLog" "Fragment shader is not compiled.
" "" "THREE.WebGLShader: gl.getShaderInfoLog() fragment
ERROR: 0:271: 'vUv' : undeclared identifier
ERROR: 0:271: 'texture2D' : no matching overloaded function found

when trying to update:

https://codepen.io/zadvorsky/pen/PNXbGo

**Comment by ampersand-alex** [comment]
change the include source between r107 and r108 on the pen settings for three.js

**Comment by Skarian** [comment]
Wanted to follow-up on above^. Library looks awesome would love to use it

**Comment by zadvorsky** [comment]
I'm working on resolving these issues, should have an updated version later today.

**Comment by zadvorsky** [comment]
I've updated the repo and published a version 3.0.0, which should work with THREE r141. There was a breaking change in a fairly recent version of three that renamed THREE.Math to THREE.MathUtils, which broke a lot of the examples and some of the utils used inside the package.
