### ISSUE TITLE
Compatibility with bufferGeometry

### ISSUE THREAD

**Issue by Prayssi** [zadvorsky/three.bas#55]
Hello, i believe the compatibility with the geometry is broken.
I tried to use ModelBufferGeometry with three.TextGeometry but ModelBufferGeometry is using the three.geometry.face's property which doesn't exist anymore.
I believe threejs moved their geometries to buffergeometry

useful link: https://stackoverflow.com/questions/42141438/access-to-faces-in-buffergeometry

Hope to hearing from you soon !

**Comment by zadvorsky** [comment]
Hello!

ModelBufferGeometry does indeed only work with the older Geometry class. It would be possible to rewrite, but I can't commit to a timeline for that. In the meantime, you can check out [this example](https://github.com/zadvorsky/three.bas/tree/master/examples/model_face_animation). You can create a Geometry instance from a BufferGeometry instance, and use that with the ModelBufferGeometry. I have an es6 export version of the older Geometry class in the examples folder of this repo (linked in the index.html of that example), which might help.
