### ISSUE TITLE
add webpack 2 instructions

### ISSUE THREAD

**Issue by clindsey** [zadvorsky/three.bas#8]
webpack 2 is pretty popular, but it requires some extra setup, we should add instructions for it.  Let's figure that out here and I'll create a PR for an updated readme.md

---

# webpack 2

## install dependencies

these are the base libraries, plus a loader that can handle the `.glsl` files

`npm install --save three three-bas shader-loader`

## webpack config

configure the loader for .glsl files, and shim THREE

```
{
  module: {
    rules: [
      { // handle shaders files
        test: /\.(glsl|vs|fs)$/,
        loader: 'shader-loader'
      }
    ]
  },
  plugins: [ // three.bas expects THREE to be globally available
    new webpack.ProvidePlugin({
      'THREE': 'three'
    })
  ]
}
```

## importing

three and bas don't have a default export, so remember to correctly reference them

```
import * as THREE from 'three'
import * as BAS from 'three-bas'
```

**Comment by zadvorsky** [comment]
Hey. Thanks for the input.

I'm a webpack novice, so if you know how to make it work I'm happy to merge a PR.

Also, I no longer expect THREE to be globally available (unless I forgot something). The namespace is now BAS (no longer THREE.BAS).

**Comment by vladnicula** [comment]
Rollup is better for libraries like this one. The compiled resulting size of rollup is smaller than the one made with webpack 2. This is the reason why libraries like Facebooks Reactjs -which is huge right now - moved to rollup recently.

**Comment by clindsey** [comment]
closing in favor of rollup
