### ISSUE TITLE
Feature request: Add LambertAnimationMaterial

### ISSUE THREAD

**Issue by supermoos** [zadvorsky/three.bas#9]
First of all, thanks for this amazing library!
It's my understanding that LambertMaterial is slightly more performant than PhongMaterial. Would be nice to add it as default material to the library :-)

**Comment by zadvorsky** [comment]
Thanks for the suggestion.

I added BAS.LambertAnimationMaterial in the new release (2.2.0).

Do note however that Lambert does not support flat shading, so you will have to compute vertex normals every time.

**Comment by supermoos** [comment]
Wow, thanks! That was fast :-)
